"""Metasploit Client — persistent msfconsole session for WSL Kali.

Uses msfconsole -q with resource scripts (one-shot) or a persistent
msfconsole subprocess (interactive).  Avoids the fragile msfrpcd RPC.
"""
from __future__ import annotations

import json
import os
import queue
import re
import subprocess
import tempfile
import threading
import time
from pathlib import Path


WSL_DISTRO = "kali-linux"
PROMPT_RE = re.compile(r"msf[0-9]?\s*>")


class MsfRpcClient:
    """Metasploit interaction via msfconsole.

    Two modes:
      * One-shot  — write a resource (.rc) script, run msfconsole -qr,
                    capture all output.
      * Interactive — keep a persistent msfconsole process (stdin/stdout)
                      for multi-command sessions.
    """

    def __init__(self) -> None:
        self._proc: subprocess.Popen | None = None
        self._out_queue: queue.Queue = queue.Queue()
        self._reader_thread: threading.Thread | None = None
        self._lock = threading.Lock()
        self._running = False

    # ── One-shot Resource Script Execution ───────────────────────────────

    def execute_script(self, rc_content: str, timeout: int = 120) -> dict:
        """Write a resource script to WSL tmp and run msfconsole -qr."""
        ts = int(time.time() * 1000)
        rc_path = f"/tmp/kai_msf_{ts}.rc"
        write_cmd = f"cat > {rc_path} << 'KAIRCEOF'\n{rc_content}\nKAIRCEOF"
        subprocess.run(
            ["wsl.exe", "-d", WSL_DISTRO, "--", "bash", "-lc", write_cmd],
            capture_output=True, timeout=15
        )
        r = subprocess.run(
            ["wsl.exe", "-d", WSL_DISTRO, "--", "bash", "-lc",
             f"msfconsole -q -r {rc_path} 2>&1; rm -f {rc_path}"],
            capture_output=True, text=True, timeout=timeout
        )
        out = (r.stdout + "\n" + r.stderr).strip()
        return {
            "ok": True,
            "output": out[:10000],
            "returncode": r.returncode,
        }

    def generate_resource_script(self, steps: list[dict]) -> str:
        """Generate a Metasploit resource (.rc) script from step definitions."""
        lines = ["# Auto-generated by K//AI"]
        for step in steps:
            action = step.get("action", "")
            if action == "use":
                lines.append(f"use {step['module']}")
            elif action == "set":
                lines.append(f"set {step['name']} {step['value']}")
            elif action == "run":
                lines.append("run -j")
            elif action == "exploit":
                lines.append("exploit -j")
            elif action == "check":
                lines.append("check")
            elif action == "sessions":
                lines.append(f"sessions -{step.get('flag', 'l')} {step.get('id', '')}")
            elif action == "resource":
                lines.append(f"resource {step.get('path', '')}")
            elif action == "raw":
                lines.append(step["command"])
            elif action == "sleep":
                lines.append(f"sleep {step.get('seconds', 3)}")
            lines.append("")
        return "\n".join(lines)

    def run_script(self, steps: list[dict], timeout: int = 120) -> dict:
        """Generate and execute a resource script from steps."""
        rc = self.generate_resource_script(steps)
        return self.execute_script(rc, timeout=timeout)

    # ── Interactive Console (persistent msfconsole) ──────────────────────

    def start_interactive(self) -> str:
        """Launch a persistent msfconsole process in WSL."""
        self.stop_interactive()
        try:
            self._proc = subprocess.Popen(
                ["wsl.exe", "-d", WSL_DISTRO, "--", "bash", "-lc",
                 "msfconsole -q --no-readline"],
                stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT, bufsize=0
            )
            self._running = True
            self._reader_thread = threading.Thread(
                target=self._reader_loop, daemon=True
            )
            self._reader_thread.start()
        except Exception as exc:
            return f"Failed to start msfconsole: {exc}"
        return "msfconsole interactive started"

    def stop_interactive(self) -> str:
        """Stop the persistent msfconsole process."""
        self._running = False
        if self._proc:
            try:
                self._proc.stdin.close()
            except Exception:
                pass
            try:
                self._proc.terminate()
                self._proc.wait(timeout=5)
            except Exception:
                try:
                    self._proc.kill()
                except Exception:
                    pass
            self._proc = None
        return "msfconsole stopped"

    @property
    def interactive_running(self) -> bool:
        return self._proc is not None and self._proc.poll() is None

    def _reader_loop(self) -> None:
        """Read stdout from msfconsole into a queue."""
        while self._running and self._proc and self._proc.stdout:
            try:
                line = self._proc.stdout.readline()
                if not line:
                    break
                self._out_queue.put(line.decode("utf-8", errors="replace"))
            except Exception:
                break

    def send_command(self, command: str, timeout: int = 30) -> dict:
        """Send a command to the interactive msfconsole and read output."""
        if not self.interactive_running:
            return {"error": "Interactive session not running"}
        try:
            with self._lock:
                self._proc.stdin.write((command + "\n").encode())
                self._proc.stdin.flush()
            lines = []
            deadline = time.time() + timeout
            while time.time() < deadline:
                try:
                    line = self._out_queue.get(timeout=2)
                    lines.append(line)
                    if PROMPT_RE.search(line):
                        break
                except queue.Empty:
                    break
            return {"output": "".join(lines)[:10000], "ok": True}
        except Exception as exc:
            return {"error": str(exc)}

    def read_all_output(self, timeout: float = 2.0) -> str:
        """Drain any buffered output (non-blocking)."""
        lines = []
        deadline = time.time() + timeout
        while time.time() < deadline:
            try:
                lines.append(self._out_queue.get(timeout=0.5))
            except queue.Empty:
                break
        return "".join(lines)

    def clear_output(self) -> None:
        """Discard buffered output."""
        while not self._out_queue.empty():
            try:
                self._out_queue.get_nowait()
            except queue.Empty:
                break

    # ── Convenience Methods ──────────────────────────────────────────────

    def get_version(self) -> dict:
        """Get Metasploit version via one-shot."""
        rc = "version\nexit\n"
        r = self.execute_script(rc)
        ver = r.get("output", "")
        m = re.search(r"Framework: ([\d.]+)", ver)
        return {
            "version": m.group(1) if m else "unknown",
            "raw": ver[:500],
        }

    def list_sessions(self) -> dict:
        """List active sessions by parsing sessions -l output."""
        rc = "sessions -l\nexit\n"
        r = self.execute_script(rc)
        out = r.get("output", "")
        sessions = {}
        for line in out.split("\n"):
            m = re.match(r"^\s*(\d+)\s+", line)
            if m:
                sid = m.group(1)
                parts = line.split()
                sessions[sid] = {
                    "id": sid,
                    "raw": line.strip()[:200],
                }
        return {"sessions": sessions, "raw_output": out[:2000]}

    def list_jobs(self) -> dict:
        """List background jobs."""
        rc = "jobs -l\nexit\n"
        r = self.execute_script(rc)
        return {"output": r.get("output", "")[:5000]}

    def db_status(self) -> dict:
        """Check database connection."""
        rc = "db_status\nexit\n"
        r = self.execute_script(rc)
        return {"output": r.get("output", "")[:2000]}

    def db_hosts(self) -> dict:
        """List hosts in MSF database."""
        rc = "hosts\nexit\n"
        r = self.execute_script(rc)
        return {"output": r.get("output", "")[:5000]}

    def execute_module(self, mod_type: str, mod_name: str,
                       options: dict | None = None) -> dict:
        """Run a module one-shot via resource script. Returns first 10k chars."""
        opts = options or {}
        lines = [f"use {mod_type}/{mod_name}"]
        for k, v in opts.items():
            lines.append(f"set {k} {v}")
        if mod_type == "exploit":
            lines.append("run -j")
        else:
            lines.append("run")
        lines.append("exit")
        rc = "\n".join(lines)
        return self.execute_script(rc)

    def execute_exploit(self, module: str, payload: str,
                        target_host: str, target_port: int | str,
                        **extra_opts) -> dict:
        """Convenience: run exploit with common options."""
        opts = {
            "RHOSTS": target_host,
            "RPORT": str(target_port),
            "PAYLOAD": payload,
            **extra_opts,
        }
        return self.execute_module("exploit", module, opts)

    def execute_auxiliary(self, module: str, target_host: str,
                          target_port: int | str = "",
                          **extra_opts) -> dict:
        """Convenience: run auxiliary module."""
        opts = {"RHOSTS": target_host}
        if target_port:
            opts["RPORT"] = str(target_port)
        opts.update(extra_opts)
        return self.execute_module("auxiliary", module, opts)

    # ── Daemon lifecycle (compatibility stubs) ───────────────────────────

    def start_daemon(self, **kwargs) -> str:
        """Stub — starts interactive instead of daemon."""
        return self.start_interactive()

    def stop_daemon(self) -> str:
        """Stub — stops interactive instead of daemon."""
        return self.stop_interactive()

    def is_daemon_running(self) -> bool:
        return self.interactive_running

    def ensure_daemon(self) -> str:
        if self.interactive_running:
            return "msfconsole already running"
        return self.start_interactive()

    def connect(self, **kwargs) -> str:
        """Stub — interactive is always ready."""
        return "Connected (interactive mode)"

    def disconnect(self) -> None:
        pass

    @property
    def connected(self) -> bool:
        return self.interactive_running
