#!/bin/bash
# Nginx + SSL Setup for Kai Enterprise on Cloud Server

set -e

echo "========================================"
echo "NGINX + SSL SETUP FOR KAI"
echo "========================================"
echo ""

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root"
   exit 1
fi

DOMAIN="trapdoorkid.cybermods.com"
EMAIL="admin@cybermods.com"

echo -e "${BLUE}[1/5] Installing Nginx and Certbot...${NC}"
apt-get install -y nginx certbot python3-certbot-nginx

echo -e "${BLUE}[2/5] Creating Nginx configuration...${NC}"
cat > /etc/nginx/sites-available/kai-enterprise << EOF
server {
    listen 80;
    server_name $DOMAIN;
    return 301 https://\$server_name\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name $DOMAIN;

    # SSL certificates (will be generated by certbot)
    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;

    # SSL configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;

    # Logging
    access_log /var/log/nginx/kai-access.log;
    error_log /var/log/nginx/kai-error.log;

    # Reverse proxy to Kai API
    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_http_version 1.1;
        
        # Headers
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        
        # WebSocket support
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Ollama API (optional, internal only)
    location /ollama/ {
        proxy_pass http://127.0.0.1:11434/;
        proxy_set_header Host \$host;
    }

    # Health check endpoint
    location /health {
        access_log off;
        return 200 "OK";
        add_header Content-Type text/plain;
    }
}
EOF

echo -e "${BLUE}[3/5] Enabling Nginx site...${NC}"
ln -sf /etc/nginx/sites-available/kai-enterprise /etc/nginx/sites-enabled/kai-enterprise
rm -f /etc/nginx/sites-enabled/default

# Test Nginx configuration
nginx -t

echo -e "${BLUE}[4/5] Requesting SSL certificate from Let's Encrypt...${NC}"
certbot certonly --nginx \
  -d $DOMAIN \
  --non-interactive \
  --agree-tos \
  --email $EMAIL \
  --expand || echo "Certificate may already exist"

echo -e "${BLUE}[5/5] Restarting Nginx...${NC}"
systemctl restart nginx
systemctl enable nginx

echo ""
echo -e "${GREEN}========================================"
echo "NGINX + SSL SETUP COMPLETE!"
echo "========================================${NC}"
echo ""
echo "Your Kai Enterprise is now available at:"
echo -e "${GREEN}https://$DOMAIN${NC}"
echo ""
echo "URLs:"
echo "  - Web UI (Swagger):  https://$DOMAIN/docs"
echo "  - API:               https://$DOMAIN/api"
echo "  - WebSocket:         wss://$DOMAIN/ws/chat"
echo ""
echo "Check status:"
echo "  systemctl status nginx"
echo "  docker-compose -f /opt/kai-enterprise/docker-compose-enterprise.yml ps"
echo ""
echo "Renew SSL certificate:"
echo "  certbot renew (automatic every 90 days)"
echo ""
